trigger:
  - main

resources:
  - repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
          - task: UseGitVersion@5
            displayName: GitVersion 
            inputs:
             versionSpec: '5.x'
          - task: Docker@2
            displayName: Build and Push image
            inputs:
              containerRegistry: 'docker-hub'
              repository: 'godeltech/codereview.analyzers.inspectcode'
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/scr/Dockerfile'
              tags: '$(Build.BuildNumber)'
